# Generated by Django 2.0.6 on 2018-08-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180805_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='images',
            new_name='image',
        ),
    ]
